import type { Agent, AuditEntry, Inquiry, Listing } from "@/types";

export const listings: Listing[] = [
  {
    id: "kilimani-2-bed",
    title: "Kilimani two-bedroom apartment",
    slug: "kilimani-two-bedroom-apartment",
    category: "Apartments",
    county: "Nairobi",
    area: "Kilimani",
    price: 95000,
    bedrooms: 2,
    bathrooms: 2,
    status: "Live",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",
    amenities: ["Balcony", "Backup power", "Parking", "Security"],
    agentId: "aisha",
    views: 1840,
    inquiries: 74,
  },
  {
    id: "nyali-maisonette",
    title: "Nyali serviced maisonette",
    slug: "nyali-serviced-maisonette",
    category: "Maisonettes",
    county: "Mombasa",
    area: "Nyali",
    price: 140000,
    bedrooms: 4,
    bathrooms: 3,
    status: "Under review",
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=900&q=80",
    amenities: ["Pool", "Garden", "Furnished", "Staff quarters"],
    agentId: "daniel",
    views: 924,
    inquiries: 31,
  },
  {
    id: "ruiru-bungalow",
    title: "Ruiru family bungalow",
    slug: "ruiru-family-bungalow",
    category: "Bungalows",
    county: "Kiambu",
    area: "Ruiru",
    price: 62000,
    bedrooms: 3,
    bathrooms: 2,
    status: "Draft",
    image: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=80",
    amenities: ["Compound", "Water tank", "Internet ready", "Pet friendly"],
    agentId: "aisha",
    views: 612,
    inquiries: 19,
  },
  {
    id: "westlands-office",
    title: "Westlands fitted office suite",
    slug: "westlands-fitted-office-suite",
    category: "Commercial",
    county: "Nairobi",
    area: "Westlands",
    price: 220000,
    bedrooms: 0,
    bathrooms: 2,
    status: "Live",
    image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=80",
    amenities: ["Lift", "Reception", "Boardroom", "Generator"],
    agentId: "mercy",
    views: 732,
    inquiries: 22,
  },
  {
    id: "thika-industrial-yard",
    title: "Thika industrial logistics yard",
    slug: "thika-industrial-logistics-yard",
    category: "Industrial",
    county: "Kiambu",
    area: "Thika",
    price: 380000,
    bedrooms: 0,
    bathrooms: 4,
    status: "Live",
    image: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=900&q=80",
    amenities: ["Truck access", "Perimeter wall", "Power", "Loading bay"],
    agentId: "mercy",
    views: 488,
    inquiries: 16,
  },
  {
    id: "diani-vacation-villa",
    title: "Diani beachfront vacation villa",
    slug: "diani-beachfront-vacation-villa",
    category: "Hospitality",
    county: "Kwale",
    area: "Diani",
    price: 35000,
    bedrooms: 5,
    bathrooms: 5,
    status: "Live",
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=900&q=80",
    amenities: ["Beach access", "Pool", "Chef kitchen", "Furnished"],
    agentId: "daniel",
    views: 1294,
    inquiries: 58,
  },
  {
    id: "naivasha-agricultural-land",
    title: "Naivasha irrigated agricultural land",
    slug: "naivasha-irrigated-agricultural-land",
    category: "Land",
    county: "Nakuru",
    area: "Naivasha",
    price: 1200000,
    bedrooms: 0,
    bathrooms: 0,
    status: "Live",
    image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=900&q=80",
    amenities: ["Water access", "Fenced", "Road frontage", "Title ready"],
    agentId: "aisha",
    views: 840,
    inquiries: 27,
  },
  {
    id: "nairobi-retail-showroom",
    title: "Nairobi CBD retail showroom",
    slug: "nairobi-cbd-retail-showroom",
    category: "Retail",
    county: "Nairobi",
    area: "CBD",
    price: 165000,
    bedrooms: 0,
    bathrooms: 1,
    status: "Live",
    image: "https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=900&q=80",
    amenities: ["Street frontage", "Storage", "Security", "Display windows"],
    agentId: "mercy",
    views: 556,
    inquiries: 21,
  },
  {
    id: "rongai-student-housing",
    title: "Rongai student housing block",
    slug: "rongai-student-housing-block",
    category: "Student housing",
    county: "Kajiado",
    area: "Ongata Rongai",
    price: 18000,
    bedrooms: 1,
    bathrooms: 1,
    status: "Live",
    image: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=900&q=80",
    amenities: ["Internet", "Study area", "Security", "Water"],
    agentId: "aisha",
    views: 1104,
    inquiries: 44,
  },
  {
    id: "upperhill-coworking",
    title: "Upper Hill co-working floor",
    slug: "upper-hill-co-working-floor",
    category: "Co-working",
    county: "Nairobi",
    area: "Upper Hill",
    price: 85000,
    bedrooms: 0,
    bathrooms: 3,
    status: "Live",
    image: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=900&q=80",
    amenities: ["Meeting rooms", "Internet", "Reception", "Kitchenette"],
    agentId: "mercy",
    views: 409,
    inquiries: 13,
  },
  {
    id: "nakuru-townhouse",
    title: "Nakuru gated townhouse",
    slug: "nakuru-gated-townhouse",
    category: "Townhouses",
    county: "Nakuru",
    area: "Milimani",
    price: 78000,
    bedrooms: 3,
    bathrooms: 3,
    status: "Live",
    image: "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?auto=format&fit=crop&w=900&q=80",
    amenities: ["Gated estate", "Parking", "Garden", "Security"],
    agentId: "daniel",
    views: 532,
    inquiries: 18,
  },
  {
    id: "lavington-penthouse",
    title: "Lavington skyline penthouse",
    slug: "lavington-skyline-penthouse",
    category: "Penthouse",
    county: "Nairobi",
    area: "Lavington",
    price: 320000,
    bedrooms: 4,
    bathrooms: 4,
    status: "Live",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=900&q=80",
    amenities: ["Private lift", "Terrace", "Gym", "Backup power"],
    agentId: "aisha",
    views: 968,
    inquiries: 35,
  },
  {
    id: "mombasa-warehouse",
    title: "Mombasa port-side warehouse",
    slug: "mombasa-port-side-warehouse",
    category: "Warehouses",
    county: "Mombasa",
    area: "Changamwe",
    price: 450000,
    bedrooms: 0,
    bathrooms: 2,
    status: "Live",
    image: "https://images.unsplash.com/photo-1553413077-190dd305871c?auto=format&fit=crop&w=900&q=80",
    amenities: ["Dock access", "High roof", "Office", "Parking"],
    agentId: "daniel",
    views: 374,
    inquiries: 12,
  },
  {
    id: "kisumu-serviced-unit",
    title: "Kisumu serviced lake-view unit",
    slug: "kisumu-serviced-lake-view-unit",
    category: "Serviced units",
    county: "Kisumu",
    area: "Milimani",
    price: 55000,
    bedrooms: 1,
    bathrooms: 1,
    status: "Live",
    image: "https://images.unsplash.com/photo-1560448075-bb485b067938?auto=format&fit=crop&w=900&q=80",
    amenities: ["Furnished", "Housekeeping", "Wi-Fi", "Lake view"],
    agentId: "aisha",
    views: 621,
    inquiries: 23,
  },
  {
    id: "eldoret-mixed-use",
    title: "Eldoret mixed-use corner block",
    slug: "eldoret-mixed-use-corner-block",
    category: "Mixed use",
    county: "Uasin Gishu",
    area: "Eldoret CBD",
    price: 210000,
    bedrooms: 0,
    bathrooms: 3,
    status: "Live",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=900&q=80",
    amenities: ["Retail frontage", "Upper offices", "Parking", "CBD access"],
    agentId: "mercy",
    views: 344,
    inquiries: 10,
  },
];

export const agents: Agent[] = [
  {
    id: "aisha",
    name: "Aisha Njeri",
    company: "Njeri Homes",
    county: "Nairobi",
    areas: ["Kilimani", "Lavington", "Ruiru"],
    rating: 4.8,
    reviews: 126,
    responseRate: 94,
    listings: 42,
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80",
    verified: true,
    bio: "Residential leasing specialist focused on verified family homes and apartments.",
  },
  {
    id: "daniel",
    name: "Daniel Otieno",
    company: "Coastline Realty",
    county: "Mombasa",
    areas: ["Nyali", "Bamburi", "Diani"],
    rating: 4.7,
    reviews: 88,
    responseRate: 91,
    listings: 27,
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80",
    verified: true,
    bio: "Coastal rentals, maisonettes and serviced short-stay homes.",
  },
  {
    id: "mercy",
    name: "Mercy Wairimu",
    company: "Metro Commercial",
    county: "Nairobi",
    areas: ["Westlands", "Upper Hill", "CBD"],
    rating: 4.9,
    reviews: 104,
    responseRate: 97,
    listings: 33,
    image: "https://images.unsplash.com/photo-1534751516642-a1af1ef26a56?auto=format&fit=crop&w=400&q=80",
    verified: true,
    bio: "Commercial spaces, office suites and landlord representation.",
  },
];

export const inquiries: Inquiry[] = [
  { id: "i-101", tenant: "Brian K.", listing: "Kilimani two-bedroom apartment", status: "Open", received: "18 minutes ago" },
  { id: "i-102", tenant: "Winnie M.", listing: "Westlands fitted office suite", status: "Replied", received: "1 hour ago" },
  { id: "i-103", tenant: "Sam O.", listing: "Ruiru family bungalow", status: "Open", received: "3 hours ago" },
];

export const auditLog: AuditEntry[] = [
  { id: "log-1", actor: "Super Admin", action: "Enabled M-Pesa payouts", target: "System settings", time: "Today 09:12" },
  { id: "log-2", actor: "Admin Grace", action: "Approved listing", target: "Kilimani two-bedroom apartment", time: "Today 08:44" },
  { id: "log-3", actor: "Admin Grace", action: "Rejected verification", target: "Agent application #KA-928", time: "Yesterday 17:20" },
];

export const dashboardStats = [
  { label: "Live listings", value: "2,418", detail: "+128 this month" },
  { label: "Verified agents", value: "384", detail: "12 awaiting review" },
  { label: "Tenant inquiries", value: "1,092", detail: "186 still open" },
  { label: "Avg response", value: "38m", detail: "94% response rate" },
];
